databases:
  - name: postgres
      ipAllowList: []

services:
  - type: web
    name: rails
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - Key: RAILS_MASTER_KEY
        Sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - type: redis
        name: redis
        ipAllowList: []
        plan: free
        maxmemoryPolicy: noeviction